In [69]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, balanced_accuracy_score, confusion_matrix, roc_curve, auc

In [70]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
dataset = pd.read_csv(url, names=names)

In [71]:
# Split the dataset
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values


In [72]:
print(len(X))
print(len(y))

150
150


In [73]:
# Encoding
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y)


In [74]:
# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)


In [75]:
# Normalization
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [91]:
# model
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(units=18, activation='tanh', input_shape=(4,)),
    tf.keras.layers.Dense(units=10, activation='tanh'),
    tf.keras.layers.Dense(units=3, activation='softmax')
])

In [92]:
# Compile
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [96]:
# Model Training
fitted_model = model.fit(X_train, y_train, epochs=40, batch_size=6)


Epoch 1/40
20/20 [==============================] - 0s 3ms/step - loss: 0.1086 - accuracy: 0.9750
Epoch 2/40
20/20 [==============================] - 0s 2ms/step - loss: 0.1061 - accuracy: 0.9750
Epoch 3/40
20/20 [==============================] - 0s 2ms/step - loss: 0.1045 - accuracy: 0.9750
Epoch 4/40
20/20 [==============================] - 0s 2ms/step - loss: 0.1033 - accuracy: 0.9750
Epoch 5/40
20/20 [==============================] - 0s 2ms/step - loss: 0.0980 - accuracy: 0.9833
Epoch 6/40
20/20 [==============================] - 0s 2ms/step - loss: 0.0968 - accuracy: 0.9750
Epoch 7/40
20/20 [==============================] - 0s 2ms/step - loss: 0.0954 - accuracy: 0.9750
Epoch 8/40
20/20 [==============================] - 0s 2ms/step - loss: 0.0923 - accuracy: 0.9750
Epoch 9/40
20/20 [==============================] - 0s 3ms/step - loss: 0.0909 - accuracy: 0.9750
Epoch 10/40
20/20 [==============================] - 0s 2ms/step - loss: 0.0900 - accuracy: 0.9750
Epoch 11/40
20/20 [

In [97]:
y_pred = model.predict(X_test)
y_pred = np.argmax(y_pred, axis=1)
acc = accuracy_score(y_test, y_pred)
balanced_acc = balanced_accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

1/1 [==============================] - 0s 22ms/step


In [100]:
# evaluation metrics
print("Accuracy: {:.2f}%".format(acc * 100))
print("Balanced Accuracy: {:.2f}%".format(balanced_acc * 100))
print("Confusion Matrix:\n", cm)

Accuracy: 96.67%
Balanced Accuracy: 97.44%
Confusion Matrix:
 [[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]


In [101]:
# fpr, tpr, thresholds = roc_curve(y_test, y_pred)
# roc_auc = auc(fpr, tpr)

In [ ]:
# print("ROC AUC Score: {:.2f}%".format(roc_auc * 100))