# Exercise 3

In [1]:
import numpy as np
import pandas as pd

#### 1) Create Two numpy array of size 3 X 2 and 2 X 3

#### 2) Randomly Initalize that array

In [7]:
A = np.random.rand(3,2)
B = np.random.rand(2,3)
print("A :")
print(A)
print("B :")
print(B)

A :
[[0.84162713 0.31657566]
 [0.6556288  0.95953026]
 [0.18124857 0.74387258]]
B :
[[0.96893742 0.57178345 0.78592429]
 [0.8625276  0.83244311 0.66631427]]


#### 3) Perform matrix multiplication

In [8]:
C = A.dot(B)
print(C)

[[1.08853927 0.74475969 0.87239409]
 [1.46288461 1.17363205 1.15462331]
 [0.81722916 0.72286654 0.63810057]]


#### 4) Perform elementwise matrix multiplication

In [9]:
D = A*B.transpose()
print(D)

[[0.81548402 0.27305524]
 [0.37487769 0.79875436]
 [0.14244766 0.49565292]]


#### 5) Find mean of first matrix

In [10]:
A.mean()

0.6164138346188658

#### 6) Convert Numeric entries(columns) of mtcars.csv to Mean Centered Version

In [12]:
datasets = pd.read_csv('/home/nihar/Downloads/mtcars.csv')
datasets.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [14]:
datasets['mpg'] = datasets['mpg'].apply(lambda x : x-datasets['mpg'].mean())
datasets['cyl'] = datasets['cyl'].apply(lambda x : x-datasets['cyl'].mean())
datasets['disp'] = datasets['disp'].apply(lambda x : x-datasets['disp'].mean())
datasets['hp'] = datasets['hp'].apply(lambda x : x-datasets['hp'].mean())
datasets['drat'] = datasets['drat'].apply(lambda x : x-datasets['drat'].mean())
datasets['wt'] = datasets['wt'].apply(lambda x : x-datasets['wt'].mean())
datasets['qsec'] = datasets['qsec'].apply(lambda x : x-datasets['qsec'].mean())
datasets['vs'] = datasets['vs'].apply(lambda x : x-datasets['vs'].mean())
datasets['am'] = datasets['am'].apply(lambda x : x-datasets['am'].mean())
datasets['gear'] = datasets['gear'].apply(lambda x : x-datasets['gear'].mean())
datasets['carb'] = datasets['carb'].apply(lambda x : x-datasets['carb'].mean())
datasets.head()

model       mpg     cyl        disp       hp      drat  \
0          Mazda RX4  0.909375 -0.1875  -70.721875 -36.6875  0.303437   
1      Mazda RX4 Wag  0.909375 -0.1875  -70.721875 -36.6875  0.303437   
2         Datsun 710  2.709375 -2.1875 -122.721875 -53.6875  0.253438   
3     Hornet 4 Drive  1.309375 -0.1875   27.278125 -36.6875 -0.516562   
4  Hornet Sportabout -1.390625  1.8125  129.278125  28.3125 -0.446563   

        wt     qsec      vs       am    gear    carb  
0 -0.59725 -1.38875 -0.4375  0.59375  0.3125  1.1875  
1 -0.34225 -0.82875 -0.4375  0.59375  0.3125  1.1875  
2 -0.89725  0.76125  0.5625  0.59375  0.3125 -1.8125  
3 -0.00225  1.59125  0.5625 -0.40625 -0.6875 -1.8125  
4  0.22275 -0.82875 -0.4375 -0.40625 -0.6875 -0.8125