In [1]:
import open3d as o3d
import numpy as np
import PIL.Image
import IPython.display
import os
import urllib
import tarfile
import gzip
import zipfile
import shutil

# Download the point cloud using below command
import wget
url = 'http://graphics.stanford.edu/pub/3Dscanrep/bunny.tar.gz'
# filename = wget.download(url)

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


### Bunny Dataset

In [2]:
# Unzip file

bunny_path = "bunny"
with tarfile.open(bunny_path + ".tar.gz") as tar:
            tar.extractall(path=os.path.dirname(bunny_path))

In [3]:
# Read file

bunny_path = "./bunny/reconstruction/bun_zipper.ply"
mesh = o3d.io.read_triangle_mesh(bunny_path)
mesh.compute_vertex_normals()

TriangleMesh with 35947 points and 69451 triangles.

In [4]:
# draw point cpoud
pcd = mesh.sample_points_uniformly(number_of_points=500)
o3d.visualization.draw_geometries([pcd])

# draw mesh
mesh.compute_vertex_normals()
o3d.visualization.draw_geometries([mesh])

### Happy Buddha Dataset

In [5]:
#Download the Happy Buddha dataset
import wget
url = 'http://graphics.stanford.edu/pub/3Dscanrep/happy/happy_recon.tar.gz'
# filename = wget.download(url)

In [6]:
# Unzip file

budha_path = "happy_recon"
with tarfile.open(budha_path + ".tar.gz") as tar:
            tar.extractall(path=os.path.dirname(budha_path))

In [7]:
# Read file

budha_path = "./happy_recon/happy_vrip.ply"
mesh_budha = o3d.io.read_triangle_mesh(budha_path)
mesh_budha.compute_vertex_normals()

TriangleMesh with 543652 points and 1087716 triangles.

In [8]:
# draw point cpoud
pcd = mesh_budha.sample_points_uniformly(number_of_points=500)
o3d.visualization.draw_geometries([pcd])

# draw mesh
mesh_budha.compute_vertex_normals()
o3d.visualization.draw_geometries([mesh_budha])

# Voxel downsampling

    1- It is a preprocessing step for point cloud processing tasks.
    2- It takes the point clouds and downsample. 
    3- Points which are in 1 voxels are averaged and we get 1 point after averaging.
    
### Why downsampling?
It makes the data of a more manageable size

Reduces the dimensionality of the data thus enabling in faster processing of the data (image)

Reducing the storage size of the data


In [9]:
# voxel downsampling on bunny dataset (reduced number of points)
print("Downsample the point cloud with a voxel of 0.05")
downpcd = pcd.voxel_down_sample(voxel_size=0.05)
o3d.visualization.draw_geometries([downpcd],width=1920, height=1080, left=50, top=50)

Downsample the point cloud with a voxel of 0.05


### Another example of Voxel downsampling

In [10]:
import numpy as np
print("Load a ply point cloud, print it, and render it")

#read_point_cloud reads a point cloud from a file. It tries to decode the file based on the extension name.
pcd = o3d.io.read_point_cloud("fragment.ply")
print(pcd)
print(np.asarray(pcd.points))

#draw_geometries visualizes the point cloud. 
o3d.visualization.draw_geometries([pcd],width=1920, height=1080, left=50, top=50)

Load a ply point cloud, print it, and render it
PointCloud with 196133 points.
[[0.65234375 0.84686458 2.37890625]
 [0.65234375 0.83984375 2.38430572]
 [0.66737998 0.83984375 2.37890625]
 ...
 [2.00839925 2.39453125 1.88671875]
 [2.00390625 2.39488506 1.88671875]
 [2.00390625 2.39453125 1.88793314]]


### Voxel downsampling

In [11]:
print("Downsample the point cloud with a voxel of 0.05")
downpcd = pcd.voxel_down_sample(voxel_size=0.05)
o3d.visualization.draw_geometries([downpcd],width=1920, height=1080, left=50, top=50)

Downsample the point cloud with a voxel of 0.05


### Crop point cloud

In [12]:
print("Load a polygon volume and use it to crop the original point cloud")

#read_selection_polygon_volume reads a json file that specifies polygon selection area. 
vol = o3d.visualization.read_selection_polygon_volume("cropped.json")

#vol.crop_point_cloud(pcd) filters out points. Only the chair remains.
chair = vol.crop_point_cloud(pcd)
o3d.visualization.draw_geometries([chair],width=1920, height=1080, left=50, top=50)

Load a polygon volume and use it to crop the original point cloud


### Paint point cloud

In [13]:
print("Paint chair")

#paint_uniform_color paints all the points to a uniform color. The color is in RGB space, [0, 1] range.
chair.paint_uniform_color([1, 0.706, 0])
o3d.visualization.draw_geometries([chair], width=1920, height=1080, left=50, top=50)

Paint chair


### Bounding Volumes
The PointCloud geometry type has bounding volumes as all other geometry types in Open3D. Currently, Open3D implements an AxisAlignedBoundingBox and an OrientedBoundingBox that can also be used to crop the geometry.


In [14]:
aabb = chair.get_axis_aligned_bounding_box()
aabb.color = (1, 0, 0)
obb = chair.get_oriented_bounding_box()
obb.color = (0, 1, 0)
o3d.visualization.draw_geometries([chair, aabb, obb])